---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honeycomb
  namespace: otel-collector
spec:
  encryptedData:
    api-key: AgAVykWukipknHuQIpdHqHPG4L8w5RlBNCfzaqQtr5O54flUesC6An1+FZtZ5/NpRjN1IyDjDx0aA6tOiE9ycaZUs6+04OYw5HRWmJF96Sul4AcWQaEGqP7er/Yi9MkE3Bep29PL60TmQQdqrcbYcOEEvPvZ7jdQBkd34nEJpe/oVwDBkn6nlB4wSycr4mWQuIhBS2ACHYHlZMw30rVVBoxu4hjHt8lu5PovVWxmV/DMA4Xe/A77BkEz9Gve8IQFjSVS2iDzacNCweveT0O+cgc0O2fOgvgw3CO3z/mShHDHPV2RhCAsY7McNyeMMeM+ilv03jNZeUWkyQkghzGCzWSWNfWi5kz9UsojH+Rh1vI+zlYvf8sVBlwtTBmyxtyPjNgdzF/KKy2oSyyym07pyeOqS5UYJxeyly6pBpTCtAqH2hfxhdd6anP32gGqpNsP+cCNCJQsMSwyUDhy0CFNMRJPXnkdAVVvn5+mz9A0+AVAiJiFAGiIl/w0Zb7D5oZ8WWustfU2FHIOzSb+q8rkdmAaV3CXeKKJgr9KrmJmeW4qviANNK5Iqb9R+NEY0mGll6ePtG532x4WDoJH4CCw1Ga4Y/N/pBWXG5moD8Vz9uFmR0WVBCE9zFk0d52XcnfGBUHD79+K9sEzGjfvhx9X2ysaVblzU9ryA1SjB/hzPYBLd0PCtieu1kAXNYLNuHIzJNtvTEyFwnNbiDQ/naLkC76RMKSff3mkONYoaUYzUoFA4Yv0Z0thKSOjbUP9+DiWV6OdtNt7WYX9hZ05NboVcy5j
  template:
    metadata:
      name: honeycomb
      namespace: otel-collector
    type: Opaque
