---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: honeycomb
  namespace: otel-collector
spec:
  encryptedData:
    api-key: AgCVRXnVolsn084g64Smp3CBM9J4T2QSnTvNfYNtUymKotU1241GmLjFuobpx8hT2yQ9cavDUIi5NOdk13ysGcz9e4aIdQpoT2tXdkVwBMJSKCYHvnwh8llbWKz1c2gEjqHSqSBWhIelGTT+nZ3ol0w8+zkSYrWpeW8OS3fwXLDoLRij5jSKPbYxOh9epTTWLXDZU5hbt897ECruiHpFeimTtEgfM4zs6rfLNTvgg4Gc798vuhnnG6u1pQA7SAyq07ekbo6fQG13mDT++sMovrVW1dZY2YmZw3OtoWmrZIzwOTk9spzI2AGLF6cGTpKk7JDGTiNe7kbS+8AeLfIVvmKG+BkUYtCv8L/+7LCggpVCEeM+LZS7W1RYRe0jQx0RBFUmuplaPQkTsMUg7gJFDiTPbbdwGCOqCQ6k1mMsDaWIASWgwy2GDGMfSdplD0sdcG+E26js20ZEPRHxvMlILkMDoZ8TclotTFEErRJcqGAOHR7hzaakAT8leQUfh1TPqj0lirb4ah4L2ore+t6gprx1+GdlXJHXoSk9Shy9dggYAsXp/fEymV1JHLhfeKbIRzFrfxLmKL/GN2CMPXG54tqDXHdDWcoEdnbFaYpZEkLubkxbv+P6LdMNy1mqEUeQwJJnw7zbT+guWclIF5M6NkIAtgHXxfvoCoT7N/SqATXScNKfgGi+t0dVNGg+CArzhyVY9uRyBF3paaRZRtU2QG7KQRoQRviyjpooL9QwotVn+erw6MtiBbNEX2hm/ksPoLMudaHtYftGlQJBewjOuOTx
  template:
    metadata:
      name: honeycomb
      namespace: otel-collector
    type: Opaque
