---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAhDcF07RvHtU7J0BQweD77WqdGxdiEfCHc6rbigatS9/S8ARv22bul7emwOiPI7zZpx1Tkj7KpcNmx5Q3ct8UFlb3aWiNf99g1oo2F1QMVr2MBMa6HqCYuWa3dOtncuNliaBSU30/O/KR5MOIH6F6m48Z1F6pQewNOvDMkO96K8BFUTCGAuR0IWGIiZyEnMtcSBuimqdHZECPcozDR+NChCX9GW2gmLJ1tYMVEFWN07+vxVNvKAJ+awn2i2nfqT/ngKVXvGnm3FKahlSndnZPXiop7Nb4U091IuKagcDb+QRYerifTMsBEHgZRZ0e0GHqKuS5+PPEOn5hcSAfaZ9y7Jsf2ZmKh63X1PoIpjIyXtEOSox3Tl3KaNHOZXvFEUVqgUfGKUb4T2SiYexqqTonU7r33kc1aFvjBZ3fYqPcEQSihp2THvgfwN+iqLMieWdojEYewY1g5h9wqyJlm1DMswJR+geoVzzKnQaE6CrqJtrRYhZEY0Fwmb5xQl8ikxyIXoSiw/EuNJZktKjIA/L6EQbc2S1w7FPPkRZwobQteHmzNNo/b/aeh/CsCzdou2V6JdYp8gi0Ur63xd1qbwRgEFJelthwIPsRNN8Z3fb05DJOJUxPx7uhh2bz5xVHpONGnWgGIkH7xuIb/2RU0XyOlKa8k1YZCikaZtz7GTm1ZBST6zFEAgnSXQEcwLPcJDLVfOPCid7IyAHuF7d4TV1+pZZvI+7Ij7Hzp5Vlsi/R/iTvyXULCuPtV
  template:
    metadata:
      name: cloudflare
      namespace: cert-manager
