---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBbXeYhjO19U6pd2AhRVyBZLVUVfPR0B8LmZwasEQ6w+UdiPxauBx7Qy438jOxixxid2W+BMTuap9CiosPBac/L/7oYTnXiDre0iBeoRqcDCQneirwwzaQpY2Q530LBkAL7mSqhNJJtgHRQtqnG4xXNZ1fhiqaNV+77L2vwuEkblGIhfnBh1udJCeC5Mw8RdmpWiq1bIiwoRlThqGYO4FhDm5SBJdtzcDBR0Lv6k/0H8zNRpzeT7H4t+BN0WCfSbqTGYpWIYgUXWwbrFeED4PEaz/uCi9lz1sRnAd9P8Bog0yDBCz4dsURmeNN8Ek5XHHLWNj/gs6YHhnJvnsKmHqGzU1HaBL0JpwPYT8i0BLY+RsUjnjLItE0UNbXnu7y1W/h6A8mBvFZmlV+CqCqiEm5eqInhhdCkrzKng/eFjJ9I2lJYzjZUxBM0j54XwudAmXGPN78rbsTBV/4N32HGMOjMJXzdRJm3gTUhgBXGDw5kH2jsmKuvs9hazAv6aALitQfE3fhcG6aItas5TAAmpxTAq2H/o0NTURy1W3BwzLvHAzwM/sGp+PiWN+wTZTRJEo1dh6kTHgr0XqZZffllcIJTb1dHml82YjfUALWrGraAnuSRZn2vINMBX4crMmR/mNME5VMwwffRzmYk6uBAVEDo2lwh0L+LNnTAhhGelt4ciCnoJy1FG7i1ln8ZWNwKq23kfhYPrH4qXmfSDOI7VNynwg1z0SL0W2wFqgSvlOgfl+EpQ0glmkoE
  template:
    metadata:
      name: cloudflare
      namespace: external-dns
